workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
      node: latest
      vars:
        XCODE_PROJECT: "ios/HomeServiceChat.xcworkspace"
        XCODE_SCHEME: "HomeServiceChat"
        BUNDLE_ID: "com.yourcompany.homeservicechat"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install
          
      - name: 修复Fabric架构问题
        script: |
          # 执行修复脚本
          echo "运行Fabric修复脚本..."
          node fix-fabric-modules.js
          
          # 执行缺失文件修复脚本
          echo "运行缺失文件修复脚本..."
          node fix-missing-fabric-files.js
          
      - name: 创建导出选项文件
        script: |
          # 创建exportOptions.plist文件支持无证书构建
          cat > ios/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>FAKE_TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.yourcompany.homeservicechat</key>
                  <string>match Development com.yourcompany.homeservicechat</string>
              </dict>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
      - name: 配置项目支持无证书构建
        script: |
          cd ios
          
          # 修改项目以支持无签名构建
          /usr/libexec/PlistBuddy -c "Add :CODE_SIGN_IDENTITY String 'Don\'t Code Sign'" HomeServiceChat.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Add :CODE_SIGNING_REQUIRED Boolean NO" HomeServiceChat.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Add :CODE_SIGNING_ALLOWED Boolean NO" HomeServiceChat.xcodeproj/project.pbxproj
          
          # 创建.xcode.env文件确保禁用新架构
          echo "export RCT_NEW_ARCH_ENABLED=0" > .xcode.env.local
          echo "export USE_FABRIC=0" >> .xcode.env.local
          echo "export USE_HERMES=0" >> .xcode.env.local
          
      - name: Build iOS app
        script: |
          cd ios
          
          # 构建无签名归档
          xcodebuild -workspace HomeServiceChat.xcworkspace \
                     -scheme HomeServiceChat \
                     -configuration Release \
                     -archivePath build/HomeServiceChat.xcarchive \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGN_ENTITLEMENTS="" \
                     DEVELOPMENT_TEAM="" \
                     archive
          
          # 导出无签名IPA
          xcodebuild -exportArchive \
                     -archivePath build/HomeServiceChat.xcarchive \
                     -exportPath build/ios \
                     -exportOptionsPlist exportOptions.plist \
                     -allowProvisioningUpdates
    artifacts:
      - build/ios/HomeServiceChat.ipa 