name: iOS Release Build

on:
  push:
    branches: [ "master", "new-master" ]
  pull_request:
    branches: [ "master", "new-master" ]
  workflow_dispatch:

jobs:
  build:
    name: iOS Build and Archive
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd ios
          pod install

      - name: Fix Fabric Architecture Issues
        run: |
          echo "执行Fabric架构修复脚本..."
          node fix-ios-fabric-complete.js
          bash run-fabric-fix.sh
          echo "Fabric架构修复完成"

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild -workspace HomeServiceChat.xcworkspace -scheme HomeServiceChat archive -archivePath $PWD/build/HomeServiceChat.xcarchive -allowProvisioningUpdates CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
      - name: Archive app
        if: success()
        run: |
          cd ios
          mkdir -p Artifacts
          xcodebuild -exportArchive -archivePath $PWD/build/HomeServiceChat.xcarchive -exportPath $PWD/Artifacts -exportOptionsPlist exportOptions.plist || true
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HomeServiceChat-iOS
          path: ios/Artifacts/
